#!/usr/bin/env bash                                                                                                               
#Create a new reminder via terminal                                                                                         
#Command line arguments: 'reminder title'
#Example run: $ ./remindmeto 'Get eggs from the shop'     
                                                                                                                                                                   
while true;
do
# loop infinitely
osascript <<END   
set reminderTitle to "Take a 15min break!"

set myDate to current date
set myNewDate to myDate + (1 * hours)

tell app "Reminders"
  tell list "Reminders" of default account
    make new reminder with properties {name:reminderTitle, due date:myNewDate}
    do shell script "echo "&"Reminder ["&reminderTitle&"] successfully created" 
  end tell
end tell                                                            
END

#Closes the reminders app once finished, remove this if you want to keep it 
#running 
killall Reminders

sleep 4500

done